# Generated by Django 4.0.3 on 2022-04-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_alter_user_managers_alter_user_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postnews",
            name="text_news",
        ),
        migrations.AddField(
            model_name="postnews",
            name="link",
            field=models.URLField(default="link"),
            preserve_default=False,
        ),
    ]
